---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, 
  message = FALSE, 
  error = FALSE, 
  warning = FALSE,
  comment = "#>"
)
```

# MODELAGEM COMPUTACIONAL DA CONCENTRAÇÃO ATMOSFÉRICA DE CO~2~ e CH~4~ NO BRASIL CENTRAL

**Resumo**:  As mudanças climáticas globais são uma preocupação mundial constante, sendo a principal causa o aumento da concentração de gases de efeito estufa (GEE) na atmosfera, especialmente o dióxido de carbono (CO~2~) e o metano (CH~4~). Para implementar medidas eficientes de mitigação das emissões de GEE, é fundamental compreender a dinâmica desses gases na atmosfera e estabelecer relações com outras variáveis associadas ao sistema solo-planta-atmosfera. Nesse contexto, diversos esforços têm sido realizados para aprimorar as técnicas de monitoramento de GEE em escala global e regional. Esta proposta tem como objetivo descrever a variabilidade espaçotemporal das concentrações atmosféricas de CO2 e CH4 em áreas do Brasil Central, identificando fontes e possíveis sumidouros desses gases ao longo dos anos de 2015 a 2023. Serão adquiridos dados das concentrações atmosféricas de CO~2~ (XCO2) e CH~4~ (XCH4) a partir dos sensores orbitais GOSAT e OCO-2. Em adição, dados das variáveis climáticas serão obtidos na plataforma da Agência Espacial Americana (NASA). Para todos os setores emissores de GEE, os dados serão obtidos a partir dos relatórios da plataforma Climate TRACE, coalizão sem fins lucrativos capaz de rastrear e fornecer informações sobre as emissões de GEE globalmente. A aquisição dos dados será sistematizada para redução das diferenças entre as resoluções espaciais dos dados de sensoriamento remoto, com posterior remoção da tendência mundial de XCO2 e XCH4. Para exploração dos dados adquiridos, serão utilizadas técnicas exploratórias multivariadas e análise geoestatística, implementadas em linguagem R. A interrelação entre as variáveis analisadas será descrita por de reconhecimento de padrão, que incluíram análises de agrupamento hierárquico e não-hierárquico, análise de componentes principais associadas aos padrões de variabilidade espacial. Espera-se que essa abordagem contribua para melhorar a compreensão da dinâmica dos gases de efeito estufa na atmosfera e suas interações com variáveis climáticas e de uso da terra no Brasil Central, auxiliando na formulação de políticas públicas voltadas para a mitigação das emissões de GEE e, principalmente, a adaptação às mudanças climáticas.

**Objetivo**: Analisar a variabilidade espaçotemporal das concentrações atmosféricas de CO2 e CH4 em áreas do Brasil Central, identificando fontes e possíveis sumidouros desses gases ao longo dos anos de 2015 a 2023, bem como suas relações com índices vegetativos e climáticos, por meio de dados de GOSAT, OCO-2 e Climate TRACE.

## 👨‍🔬 Autores

-   **Pedro Henrique Marucio de Oliveira**\
    Graduando em Agronomia - FCAV/Unesp\
    Email: [pedro.marucio\@unesp.br](mailto:pedro.marucio@unesp.b)


-   **Prof. Dr. Alan Rodrigo Panosso**\
    Coorientador — Departamento de Ciências Exatas - FCAV/Unesp\
    Email: [alan.panosso\@unesp.br](mailto:alan.panosso@unesp.br)

## 📁 Etapas do Projeto

Os scripts abaixo foram desenvolvidos em RMarkdown e estão disponíveis em formato HTML:

 - **Aquisição e download dos dados brutos** **[ATUALIZAR_PEDRO]**
    -   [GOSAT](https://www.gosat.nies.go.jp/): Dados de concentração de CO~2~ e CH~4~\
    -   [OCO-2](https://oco.jpl.nasa.gov/): Dados de concentração de CO~2~\
    -   [Climate TRACE](https://climatetrace.org/): Dados de emissões de GEE\
    -   [NASA](https://climate.nasa.gov/): Dados climáticos\

-   [`01_faxina_tratamento_dados`](https://arpanosso.github.io//projeto-oliveiraphm//01_faxina_tratamento_dados.html) – Faxina, filtragem e organização dos dados.\

-   [`02_preprocessamento`](https://arpanosso.github.io//projeto-oliveiraphm//02_preprocessamento.html) – Preparação dos dados para análise.

## 👉 [DOWNLOAD A BASE](https://drive.google.com/file/d/1EbGu6pI62J9fTxx2roxeRx6_WL4pZsbG/view?usp=drive_link)
