---
title: "01_faxina_tratamento_dados"
author: "Oliveria, PHM; Panosso, AR"
date: "2025-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r, eval = FALSE}
# Faxina - XCO2 -----------------------------------------------------------

# ## Lista com caminho e nomes dos arquivo a serem lidos - xco2
# list_of_files <- list.files("data-raw/nc4/",
#                             pattern = ".nc4",
#                             full.names = TRUE)
#
# ## buscando o contorno do Brasil
# br <- geobr::read_country(showProgress = FALSE)
# pol_br <- br$geom |> purrr::pluck(1) |> as.matrix()
# def_pol <- function(x, y, pol){
#   as.logical(sp::point.in.polygon(point.x = x,
#                                   point.y = y,
#                                   pol.x = pol[,1],
#                                   pol.y = pol[,2]))
# }
#
# ## função para ler arquivos NCD4
# ncdf_reader <- function(file_path){
#   nc_file <- ncdf4::nc_open(file_path)
#   df <- data.frame(
#     "longitude"=ncdf4::ncvar_get(nc_file,varid="longitude"),
#     "latitude"=ncdf4::ncvar_get(nc_file,varid="latitude"),
#     "time"=ncdf4::ncvar_get(nc_file,varid="time"),
#     "xco2"=ncdf4::ncvar_get(nc_file,varid="xco2"),
#     "xco2_quality_flag"=ncdf4::ncvar_get(nc_file,varid="xco2_quality_flag"),
#     "xco2_incerteza"=ncdf4::ncvar_get(nc_file,varid="xco2_uncertainty"),
#     "path" = file_path
#   )
#   ncdf4::nc_close(nc_file)
#   return(df)
# }
# ncdf_reader(list_of_files[1])
# dff_1 <- purrr::map_df(list_of_files[1:1000],ncdf_reader)
# readr::write_rds(dff_1,"data-raw/dff_1.rds")
# dff_2 <- purrr::map_df(list_of_files[1001:2000],ncdf_reader)
# readr::write_rds(dff_2,"data-raw/dff_2.rds")
# dff_3 <- purrr::map_df(list_of_files[2001:length(list_of_files)],ncdf_reader)
# readr::write_rds(dff_3,"data-raw/dff_3.rds")
#
# df1 <- readr::read_rds("data-raw/dff_1.rds")
# df1 <- df1 |>
#   dplyr::filter(longitude >= -80 &
#                   longitude <= -32,
#                 latitude >= -34 &
#                   latitude <= 10)
# dplyr::glimpse(df1)
#
# df2 <- readr::read_rds("data-raw/dff_2.rds")
# df2 <- df2 |>
#   dplyr::filter(longitude >= -80 &
#                   longitude <= -32,
#                 latitude >= -34 &
#                   latitude <= 10)
# dplyr::glimpse(df2)
#
# df3 <- readr::read_rds("data-raw/dff_3.rds")
# df3 <- df3 |>
#   dplyr::filter(longitude >= -80 &
#                   longitude <= -32,
#                 latitude >= -34 &
#                   latitude <= 10)
# dplyr::glimpse(df3)
# dff <- rbind(df1,df2,df3)
#
# dff <- dff |>
#   dplyr::mutate(
#     flag_br = def_pol(longitude, latitude, pol_br)
#   )
# dplyr::glimpse(dff)
#
# regiao <- geobr::read_region(showProgress = FALSE)
# pol_norte <- regiao$geom |> purrr::pluck(1) |> as.matrix()
# pol_nordeste <- regiao$geom |> purrr::pluck(2) |> as.matrix()
# pol_sudeste <- regiao$geom |> purrr::pluck(3) |> as.matrix()
# pol_sul <- regiao$geom |> purrr::pluck(4) |> as.matrix()
# pol_centroeste<- regiao$geom |> purrr::pluck(5) |> as.matrix()
#
# # Retirando alguns pontos
# pol_br <- pol_br[pol_br[,1]<=-34,]
# pol_br <- pol_br[!((pol_br[,1]>=-38.8 & pol_br[,1]<=-38.6) &
#                      (pol_br[,2]>= -19 & pol_br[,2]<= -16)),]
#
# pol_nordeste <- pol_nordeste[pol_nordeste[,1]<=-34,]
# pol_nordeste <- pol_nordeste[!((pol_nordeste[,1]>=-38.7 & pol_nordeste[,1]<=-38.6) & pol_nordeste[,2]<= -15),]
#
# # Retirando alguns pontos
# pol_br <- pol_br[pol_br[,1]<=-34,]
# pol_br <- pol_br[!((pol_br[,1]>=-38.8 & pol_br[,1]<=-38.6) &
#                      (pol_br[,2]>= -19 & pol_br[,2]<= -16)),]
#
# pol_nordeste <- pol_nordeste[pol_nordeste[,1]<=-34,]
# pol_nordeste <- pol_nordeste[!((pol_nordeste[,1]>=-38.7 & pol_nordeste[,1]<=-38.6) & pol_nordeste[,2]<= -15),]
#
# # Recriando o flag_nordeste
# dff <- dff |>
#   dplyr::mutate(
#     flag_br = def_pol(longitude, latitude, pol_br),
#     flag_nordeste = def_pol(longitude, latitude, pol_nordeste)
#   )
#
# br |>
#   ggplot2::ggplot() +
#   ggplot2::geom_sf(fill="white", color="#FEBF57",
#                    size=.15, show.legend = FALSE) +
#   ggplot2::geom_point(data= dff |>
#                         dplyr::sample_n(10000) |>
#                         dplyr::filter(flag_br|flag_nordeste) ,
#                       ggplot2::aes(x=longitude,y=latitude),
#                       shape=3,
#                       col="red",
#                       alpha=0.2)

# dff <- dff |>
#   dplyr::filter(flag_br|flag_nordeste)
# data_set <- readr::read_rds("data/nasa-xco2.rds") |>
#   # tibble::tibble() |>
#   dplyr::filter(
#     xco2 > 0,
#     xco2_quality_flag == 0) |>
#     dplyr::mutate(
#       path = stringr::str_remove(path, "data-raw/nc4/|\\.nc4"),
#       date = lubridate::as_date(stringr::str_sub(path,12,17)),
#       year = lubridate::year(date),
#       month = lubridate::month(date),
#       day = lubridate::day(date),
#       .after = "time"
#     )
# dplyr::glimpse(data_set)

# # Criando a coluna para os estados.
# # carregando os poligonos e funções
# source("R/my-function.R")
#
# # Leitura do banco de dados
# data_set <- readr::read_rds("data/nasa-xco2.rds")
#
# # Classificando pontos
# state <- 0
# x <- data_set |> dplyr::pull(longitude)
# y <- data_set |> dplyr::pull(latitude)
# for(i in 1:nrow(data_set)) state[i] <- get_geobr_state(x[i],y[i])
# data_set <- data_set |> cbind(state)
# dplyr::glimpse(data_set)


# readr::write_rds(data_set,"data/nasa-xco2.rds")


# Faxina xCH4 -------------------------------------------------------------
# ## Lista com caminho e nomes dos arquivo a serem lidos - xco2
# list_of_files <- list.files("data-raw/CH4_GOS_OCPR/",
#                             pattern = ".nc",
#                             full.names = TRUE,
#                             all.files = TRUE,
#                             recursive = TRUE)
#
# # buscando o contorno do Brasil
# br <- geobr::read_country(showProgress = FALSE)
# pol_br <- br$geom |> purrr::pluck(1) |> as.matrix()
# def_pol <- function(x, y, pol){
#   as.logical(sp::point.in.polygon(point.x = x,
#                                   point.y = y,
#                                   pol.x = pol[,1],
#                                   pol.y = pol[,2]))
# }
#
#
# ## função para ler arquivos NCD4
# ncdf_reader <- function(file_path){
#   nc_file <- ncdf4::nc_open(file_path)
#   df <- data.frame(
#     "longitude"=ncdf4::ncvar_get(nc_file,varid="longitude"),
#     "latitude"=ncdf4::ncvar_get(nc_file,varid="latitude"),
#     "time"=ncdf4::ncvar_get(nc_file,varid="time"),
#     "xch4"=ncdf4::ncvar_get(nc_file,varid="xch4"),
#     "xch4_quality_flag"=ncdf4::ncvar_get(nc_file,varid="xch4_quality_flag"),
#     "xch4_incerteza"=ncdf4::ncvar_get(nc_file,varid="xch4_uncertainty"),
#     "path" = file_path
#   )
#   ncdf4::nc_close(nc_file)
#   return(df)
# }
#
#
# dff_1 <- purrr::map_df(list_of_files[1:1000],ncdf_reader)
# readr::write_rds(dff_1,"data-raw/dff_1.rds")
# dff_2 <- purrr::map_df(list_of_files[1001:2000],ncdf_reader)
# readr::write_rds(dff_2,"data-raw/dff_2.rds")
# dff_3 <- purrr::map_df(list_of_files[2001:3000],ncdf_reader)
# readr::write_rds(dff_3,"data-raw/dff_3.rds")
# dff_4 <- purrr::map_df(list_of_files[3001:length(list_of_files)],ncdf_reader)
# readr::write_rds(dff_4,"data-raw/dff_4.rds")
#
#
#
# df1 <- readr::read_rds("data-raw/dff_1.rds")
# df1 <- df1 |>
#   dplyr::filter(longitude >= -80 &
#                   longitude <= -32,
#                 latitude >= -34 &
#                   latitude <= 10)
# dplyr::glimpse(df1)
#
# df2 <- readr::read_rds("data-raw/dff_2.rds") |>
#   dplyr::filter(longitude >= -80 &
#                   longitude <= -32,
#                 latitude >= -34 &
#                   latitude <= 10)
# dplyr::glimpse(df2)
#
# df3 <- readr::read_rds("data-raw/dff_3.rds") |>
#   dplyr::filter(longitude >= -80 &
#                   longitude <= -32,
#                 latitude >= -34 &
#                   latitude <= 10)
# dplyr::glimpse(df3)
#
# df4 <- readr::read_rds("data-raw/dff_4.rds") |>
#   dplyr::filter(longitude >= -80 &
#                   longitude <= -32,
#                 latitude >= -34 &
#                   latitude <= 10)
# dplyr::glimpse(df3)
# dff <- rbind(df1,df2,df3,df4)
#
# dff <- dff |>
#   dplyr::mutate(
#     flag_br = def_pol(longitude, latitude, pol_br)
#   )
# dplyr::glimpse(dff)

# regiao <- geobr::read_region(showProgress = FALSE)
# pol_norte <- regiao$geom |> purrr::pluck(1) |> as.matrix()
# pol_nordeste <- regiao$geom |> purrr::pluck(2) |> as.matrix()
# pol_sudeste <- regiao$geom |> purrr::pluck(3) |> as.matrix()
# pol_sul <- regiao$geom |> purrr::pluck(4) |> as.matrix()
# pol_centroeste<- regiao$geom |> purrr::pluck(5) |> as.matrix()
#
# # Retirando alguns pontos
# pol_br <- pol_br[pol_br[,1]<=-34,]
# pol_br <- pol_br[!((pol_br[,1]>=-38.8 & pol_br[,1]<=-38.6) &
#                      (pol_br[,2]>= -19 & pol_br[,2]<= -16)),]
#
# pol_nordeste <- pol_nordeste[pol_nordeste[,1]<=-34,]
# pol_nordeste <- pol_nordeste[!((pol_nordeste[,1]>=-38.7 & pol_nordeste[,1]<=-38.6) & pol_nordeste[,2]<= -15),]
#
# # Retirando alguns pontos
# pol_br <- pol_br[pol_br[,1]<=-34,]
# pol_br <- pol_br[!((pol_br[,1]>=-38.8 & pol_br[,1]<=-38.6) &
#                      (pol_br[,2]>= -19 & pol_br[,2]<= -16)),]
#
# pol_nordeste <- pol_nordeste[pol_nordeste[,1]<=-34,]
# pol_nordeste <- pol_nordeste[!((pol_nordeste[,1]>=-38.7 & pol_nordeste[,1]<=-38.6) & pol_nordeste[,2]<= -15),]
#
# # Recriando o flag_nordeste
# dff <- dff |>
#   dplyr::mutate(
#     flag_br = def_pol(longitude, latitude, pol_br),
#     flag_nordeste = def_pol(longitude, latitude, pol_nordeste)
#   )
#
# br |>
#   ggplot2::ggplot() +
#   ggplot2::geom_sf(fill="white", color="#FEBF57",
#                    size=.15, show.legend = FALSE) +
#   ggplot2::geom_point(data= dff |>
#                         dplyr::sample_n(10000) |>
#                         dplyr::filter(flag_br|flag_nordeste) ,
#                       ggplot2::aes(x=longitude,y=latitude),
#                       shape=3,
#                       col="red",
#                       alpha=0.2)


# data_set <- dff |>
#   dplyr::filter(flag_br|flag_nordeste) |>
#   dplyr::filter(
#     xch4 > 0,
#     xch4_quality_flag == 0) |>
#     dplyr::mutate(
#       path = stringr::str_remove(path, "data-raw/CH4_GOS_OCPR/20...|\\.nc"),
#       date = lubridate::as_date(stringr::str_sub(path,27,34)),
#       year = lubridate::year(date),
#       month = lubridate::month(date),
#       day = lubridate::day(date),
#       .after = "time"
#     )
# dplyr::glimpse(data_set)
#
# # Criando a coluna para os estados.
# # carregando os poligonos e funções
# source("R/my-function.R")
#
# # Classificando pontos
# state <- 0
# x <- data_set |> dplyr::pull(longitude)
# y <- data_set |> dplyr::pull(latitude)
# for(i in 1:nrow(data_set)) state[i] <- get_geobr_state(x[i],y[i])
# data_set <- data_set |> cbind(state)
# dplyr::glimpse(data_set)
# readr::write_rds(data_set,"data/gosat-xch4.rds")


# Faxina para a SIF -------------------------------------------------------
# buscando o contorno do Brasil
# br <- geobr::read_country(showProgress = FALSE)
# pol_br <- br$geom |> purrr::pluck(1) |> as.matrix()
# def_pol <- function(x, y, pol){
#   as.logical(sp::point.in.polygon(point.x = x,
#                                   point.y = y,
#                                   pol.x = pol[,1],
#                                   pol.y = pol[,2]))
# }
# dff <- fco2r::oco2_br |>
#   dplyr::mutate(
#     xco2 = xco2_moles_mole_1*1e06,
#     date = lubridate::ymd_hms(time_yyyymmddhhmmss),
#     year = lubridate::year(date),
#     month = lubridate::month(date),
#     day = lubridate::day(date),
#     sif = (
#       fluorescence_radiance_757nm_idp_ph_sec_1_m_2_sr_1_um_1*2.6250912*10^(-19)  + 1.5*fluorescence_radiance_771nm_idp_ph_sec_1_m_2_sr_1_um_1* 2.57743*10^(-19))/2)
#
# regiao <- geobr::read_region(showProgress = FALSE)
# pol_norte <- regiao$geom |> purrr::pluck(1) |> as.matrix()
# pol_nordeste <- regiao$geom |> purrr::pluck(2) |> as.matrix()
# pol_sudeste <- regiao$geom |> purrr::pluck(3) |> as.matrix()
# pol_sul <- regiao$geom |> purrr::pluck(4) |> as.matrix()
# pol_centroeste<- regiao$geom |> purrr::pluck(5) |> as.matrix()
#
# # Retirando alguns pontos
# pol_br <- pol_br[pol_br[,1]<=-34,]
# pol_br <- pol_br[!((pol_br[,1]>=-38.8 & pol_br[,1]<=-38.6) &
#                      (pol_br[,2]>= -19 & pol_br[,2]<= -16)),]
#
# pol_nordeste <- pol_nordeste[pol_nordeste[,1]<=-34,]
# pol_nordeste <- pol_nordeste[!((pol_nordeste[,1]>=-38.7 & pol_nordeste[,1]<=-38.6) & pol_nordeste[,2]<= -15),]
#
# # Retirando alguns pontos
# pol_br <- pol_br[pol_br[,1]<=-34,]
# pol_br <- pol_br[!((pol_br[,1]>=-38.8 & pol_br[,1]<=-38.6) &
#                      (pol_br[,2]>= -19 & pol_br[,2]<= -16)),]
#
# pol_nordeste <- pol_nordeste[pol_nordeste[,1]<=-34,]
# pol_nordeste <- pol_nordeste[!((pol_nordeste[,1]>=-38.7 & pol_nordeste[,1]<=-38.6) & pol_nordeste[,2]<= -15),]
#
# # Recriando o flag_nordeste
# dff <- dff |>
#   dplyr::mutate(
#     flag_br = def_pol(longitude, latitude, pol_br),
#     flag_nordeste = def_pol(longitude, latitude, pol_nordeste)
#   )
#
# br |>
#   ggplot2::ggplot() +
#   ggplot2::geom_sf(fill="white", color="#FEBF57",
#                    size=.15, show.legend = FALSE) +
#   ggplot2::geom_point(data= dff |>
#                         dplyr::sample_n(1000) |>
#                         dplyr::filter(flag_br|flag_nordeste) ,
#                       ggplot2::aes(x=longitude,y=latitude),
#                       shape=3,
#                       col="red",
#                       alpha=0.2)
#
#
# # Criando a coluna para os estados.
# # carregando os poligonos e funções
# source("R/my-function.R")
#
# # Classificando pontos
#
# data_set <- dff
# state <- 0
# x <- data_set |> dplyr::pull(longitude)
# y <- data_set |> dplyr::pull(latitude)
# for(i in 1:nrow(data_set)) state[i] <- get_geobr_state(x[i],y[i])
# data_set <- data_set |> cbind(state)
# dplyr::glimpse(data_set)
# readr::write_rds(data_set,"data/oco2-sif.rds")
#

# Faxina appeears ---------------------------------------------------------
## Lista com caminho e nomes dos arquivo a serem lidos - xco2
list_of_files <- list.files("data-raw/appeears/",
                            pattern = ".nc",
                            full.names = TRUE)


nc_obj_1<-ncdf4::nc_open(list_of_files[1]); names(nc_obj_1[['var']])
nc_obj_2<-ncdf4::nc_open(list_of_files[2]); names(nc_obj_2[['var']])
nc_obj_3<-ncdf4::nc_open(list_of_files[3]); names(nc_obj_3[['var']])
memory.limit()
df <- data.frame(
  "EVI"=ncdf4::ncvar_get(nc_obj_1,varid="_250m_16_days_EVI"),
  # "latitude"=ncdf4::ncvar_get(nc_file,varid="latitude"),
  # "time"=ncdf4::ncvar_get(nc_file,varid="time"),
  # "xco2"=ncdf4::ncvar_get(nc_file,varid="xco2"),
  # "xco2_quality_flag"=ncdf4::ncvar_get(nc_file,varid="xco2_quality_flag"),
  # "xco2_incerteza"=ncdf4::ncvar_get(nc_file,varid="xco2_uncertainty"),
  # "path" = file_path
)



## função para ler arquivos NCD4
ncdf_reader <- function(file_path){
  nc_file <- ncdf4::nc_open(file_path)
  df <- data.frame(
    "longitude"=ncdf4::ncvar_get(nc_file,varid="longitude"),
    "latitude"=ncdf4::ncvar_get(nc_file,varid="latitude"),
    "time"=ncdf4::ncvar_get(nc_file,varid="time"),
    "xco2"=ncdf4::ncvar_get(nc_file,varid="xco2"),
    "xco2_quality_flag"=ncdf4::ncvar_get(nc_file,varid="xco2_quality_flag"),
    "xco2_incerteza"=ncdf4::ncvar_get(nc_file,varid="xco2_uncertainty"),
    "path" = file_path
  )
  ncdf4::nc_close(nc_file)
  return(df)
}


## buscando o contorno do Brasil
br <- geobr::read_country(showProgress = FALSE)
pol_br <- br$geom |> purrr::pluck(1) |> as.matrix()
def_pol <- function(x, y, pol){
  as.logical(sp::point.in.polygon(point.x = x,
                                  point.y = y,
                                  pol.x = pol[,1],
                                  pol.y = pol[,2]))
}

```

